### ISSUE TITLE
Pyinstaller making youtube-search-python unusable

### ISSUE THREAD

**Issue by FirePlank** [alexmercerind/youtube-search-python#42] opened 2021-01-05 14:56 UTC
So i have this line of code in one of my cogs in my discord.py bot that works perfectly fine normally but when i make it an exe it gives me this error:

`
Traceback (most recent call last):
  File "discord\ext\commands\core.py", line 85, in wrapped
  File "C:\Users\FIREPL~1\AppData\Local\Temp\_MEI99962\cogs\music.py", line 446, in _play
    search = VideosSearch(search, limit=1).result()['result'][0]['link']
  File "youtubesearchpython\search.py", line 142, in __init__
  File "youtubesearchpython\internal\search.py", line 20, in __init__
  File "youtubesearchpython\handlers\requesthandler.py", line 12, in __makeRequest
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\FIREPL~1\\AppData\\Local\\Temp\\_MEI99962\\youtubesearchpython\\requestPayload.json'
`

Is there any way to fix this error?

**Comment by alexmercerind** [comment] 2021-01-05 16:22
Hi there @FirePlank !

You may see in your error log that your your executable is unable to find a file called "request payload.json" which is a part of this library.
Possibly the way you are generating is unable to deal with non Python files.

What I can do on my end, is remove the file completely & store its content inside one of the Python files itself.

Although its not a bug in this library, but I'll change the things, so that it works for you.

Greetings.

**Comment by FirePlank** [comment] 2021-01-05 16:24
thank you! The exe can open non-python files like a .txt file and a .json file for my database so I'm not sure why it's unable to work, but the fix you provide might just do the trick.

**Comment by alexmercerind** [comment] 2021-01-05 17:10
Hi there @FirePlank !

Please update version to v1.3.5 on PyPI. Let me know if it works fine.

Closing issue. Feel free to reopen.

**Closed by alexmercerind** 2021-01-05 17:10 UTC
