### ISSUE TITLE
Playlist result Not "tab delimited" in JSON ResultMode

### ISSUE THREAD

**Issue by sosfan** [alexmercerind/youtube-search-python#113] opened 2021-09-15 18:52 UTC
Apparently the playlist queries return the json code on a single line.

**Comment by mytja** [comment] 2021-09-15 19:04
I will fix this tomorrow

**Comment by raitonoberu** [comment] 2021-09-16 01:24
You can add as many indents as you want:
```py
import json
...
result = search.result()
result_json = json.dumps(result, indent=5)
```

**Comment by mytja** [comment] 2021-09-16 04:58
> You can add as many indents as you want:
> 
> ```python
> import json
> ...
> result = search.result()
> result_json = json.dumps(result, indent=5)
> ```

Yeah, but the problem is, they are passing ResultMode.JSON and not getting JSON back. Instead they get back the dictionary. This is a problem that was introduced I think with my PR, since I rewrote a lot of class. I will fix this today, and afterwards release it to PyPI.

BTW thanks for closing a couple of issues for me

**Comment by raitonoberu** [comment] 2021-09-16 05:21
I can't reproduce it.
```py
import youtubesearchpython as yt
search = yt.VideosSearch("say it aint so")

rjson = search.result(yt.ResultMode.json)
print(type(rjson) == str)
# True
print("        " in rjson)
# True

rdict = search.result(yt.ResultMode.dict)
print(type(rdict) == dict)
# True
``

**Comment by mytja** [comment] 2021-09-16 05:36
> I can't reproduce it.
> 
> ```python
> import youtubesearchpython as yt
> search = yt.VideosSearch("say it aint so")
> 
> rjson = search.result(yt.ResultMode.json)
> print(type(rjson) == str)
> # True
> print("        " in rjson)
> # True
> 
> rdict = search.result(yt.ResultMode.dict)
> print(type(rdict) == dict)
> # True
> ```

Playlist class, not VideosSearch class

![playlist](https://user-images.githubusercontent.com/52399966/133555572-3efe27ff-9a19-465c-ae05-3b76e6953334.PNG)

**Closed** 2021-09-16 05:37 UTC
Labels: bug

**Comment by mytja** [comment] 2021-09-16 05:57
Ok, this is now fixed.
