### ISSUE TITLE
Number of views is not correct

### ISSUE THREAD

**Issue by saturnus-ringar** [alexmercerind/youtube-search-python#22] opened 2020-09-17 14:18 UTC
Thanks for the great library. Nevertheless when I do a search on: "Madonna Hung Up" I get these results:
```
{'channel': 'Madonna',
 'duration': '5:27',
 'id': 'EDwb9jOVRtU',
 'index': 0,
 'link': 'https://www.youtube.com/watch?v=EDwb9jOVRtU',
 'thumbnails': ['https://img.youtube.com/vi/EDwb9jOVRtU/default.jpg',
                'https://img.youtube.com/vi/EDwb9jOVRtU/hqdefault.jpg',
                'https://img.youtube.com/vi/EDwb9jOVRtU/mqdefault.jpg',
                'https://img.youtube.com/vi/EDwb9jOVRtU/sddefault.jpg',
                'https://img.youtube.com/vi/EDwb9jOVRtU/maxresdefault.jpg'],
 'title': 'Madonna - Hung Up (Official Music Video)',
 'views': 268}
```

It seems like the number of views (269 036 248) isn't parsed correctly. Seems like this line could be the culprit:
https://github.com/alexmercerind/youtube-search-python/blob/cdfd4ff16ef45a00c448983586b4fcc7cd8ef123/youtubesearchpython/videos__scripthandler.py
`for character in self.pageSource[index+2].split()[0]:`

**Comment by alexmercerind** [comment] 2020-09-17 14:28
@saturnus-ringar,
Okay... Let me see. I'll give you update soon.

Thanks for your feedback.

**Comment by alexmercerind** [comment] 2020-09-17 14:55
Hi @saturnus-ringar,

I'm unable to reproduce the issue you mentioned.

**However, I might be able to help you, if you provide me a .txt document with string stored in ```self.page```.**
You can generate one with the following script:
```py
search = SearchVideos("Madonna Hung Up", offset = 1, mode = "json", max_results = 20)
with open('log.txt', 'w', encoding = 'utf_8') as log:
    log.write(search.page)
print(search.result())
```

My search result is giving correct response, as follows:

```json
{
    "search_result": [
        {
            "index": 0,
            "id": "EDwb9jOVRtU",
            "link": "https://www.youtube.com/watch?v=EDwb9jOVRtU",
            "title": "Madonna - Hung Up (Official Music Video)",
            "channel": "Madonna",
            "duration": "5:27",
            "views": 268876210,
            "thumbnails": [
                "https://img.youtube.com/vi/EDwb9jOVRtU/default.jpg",
                "https://img.youtube.com/vi/EDwb9jOVRtU/hqdefault.jpg",
                "https://img.youtube.com/vi/EDwb9jOVRtU/mqdefault.jpg",
                "https://img.youtube.com/vi/EDwb9jOVRtU/sddefault.jpg",
                "https://img.youtube.com/vi/EDwb9jOVRtU/maxresdefault.jpg"
            ]
        },
...
```

**Comment by alexmercerind** [comment] 2020-09-17 17:43
Give me some feedback according to the comment above. ❎ I'm closing this for now.

Feel free to reopen 😃!

**Closed by alexmercerind** 2020-09-17 17:43 UTC
Labels: needs info

**Comment by saturnus-ringar** [comment] 2020-09-18 07:00
Thanks for looking into this. Here is the txt-results:
https://pastebin.com/V3hkakK4
... I'm using Python 3.8.5.

**Comment by alexmercerind** [comment] 2020-09-18 07:08
Hi @saturnus-ringar,

Thanks for your information. Expect the issue to be fixed quickly.

Thankyou.

**Comment by alexmercerind** [comment] 2020-09-18 07:28
🎉 @saturnus-ringar,

Please try out the library from master of the repo.

Let me know if your issue gets resolved.

**Comment by saturnus-ringar** [comment] 2020-09-18 08:46
Yes, it works. The number of views is now 269103180. Thanks for the fix!

**Comment by saturnus-ringar** [comment] 2020-10-13 11:16
I've encountered an issue with the number of views. views end up as "LIVE". Here's how to reproduce the issue:
` for result in json.loads(SearchVideos("Generation Underground Shooken to the Core", offset=1, mode="json", max_results=1).result())["search_result"]:
            print(result["views"])
`
