### ISSUE TITLE
StreamURLFetcher is failing for age restricted videos

### ISSUE THREAD

**Issue by 89z** [alexmercerind/youtube-search-python#95] opened 2021-07-24 23:53 UTC
~~~
curl -v -L 'https://youtube.com/get_video_info?c=TVHTML5&cver=7.20201028&eurl=https://youtube.googleapis.com/v/EGfBezxVfWM&sts=&video_id=EGfBezxVfWM'
HTTP/2 404
~~~

**Comment by mytja** [comment] 2021-07-25 16:57
Get video info works just fine. Please use current youtube-search-python version. In your curl request, you also need to provide data, which as you can see here
https://github.com/alexmercerind/youtube-search-python/blob/539137a435a63a59612f69ba85a501ca768c12d7/youtubesearchpython/internal/streamurlfetcher.py#L45
is only empty string encoded to bytes.
Please only open issues related to this library and not your own "solutions".
Thanks

**Comment by 89z** [comment] 2021-07-25 17:06
What youve just said can be easily disproven. Its obvious that you didnt even test what you are saying, which is disappointing:

~~~py
from urllib.request import urlopen
from urllib.parse import parse_qs, urlencode

response = urlopen(
  'https://youtube.com/get_video_info' + '?' + urlencode({
      'video_id': 'OMsCQPmHQSo',
      'eurl': 'https://youtube.googleapis.com/v/OMsCQPmHQSo',
      'sts': '',
      "c": "TVHTML5",
      "cver": "7.20201028"
  }),
  data = ''.encode('utf_8'),
  timeout = None,
)

# urllib.error.HTTPError: HTTP Error 404: Not Found
print(response)
~~~

**Comment by mytja** [comment] 2021-07-25 17:12
> What youve just said can be easily disproven. Its obvious that you didnt even test what you are saying, which is disappointing:
> 
> ```python
> from urllib.request import urlopen
> from urllib.parse import parse_qs, urlencode
> 
> response = urlopen(
>   'https://youtube.com/get_video_info' + '?' + urlencode({
>       'video_id': 'OMsCQPmHQSo',
>       'eurl': 'https://youtube.googleapis.com/v/OMsCQPmHQSo',
>       'sts': '',
>       "c": "TVHTML5",
>       "cver": "7.20201028"
>   }),
>   data = ''.encode('utf_8'),
>   timeout = None,
> )
> 
> print(response) # urllib.error.HTTPError: HTTP Error 404: Not Found
> ```

I have clearly tested it, and here is proof:
![ytsearchissue](https://user-images.githubusercontent.com/52399966/126907510-22cc82d9-5f2a-44ad-9425-8048747f1316.PNG)

**Comment by mytja** [comment] 2021-07-25 17:25
[This](https://github.com/alexmercerind/youtube-search-python/blob/539137a435a63a59612f69ba85a501ca768c12d7/youtubesearchpython/internal/streamurlfetcher.py#L37) is used in age-restricted videos - but I don't know if it works in not age-restricted videos (I assume not) - as you can clearly see from previous line (comment).
[This](https://github.com/alexmercerind/youtube-search-python/blob/539137a435a63a59612f69ba85a501ca768c12d7/youtubesearchpython/internal/extras.py#L8) class directly parses YouTube's response (with stream URLs). StreamURLFetcher only descrambles those and then returns it.

**Comment by 89z** [comment] 2021-07-25 17:25
What you screenshot conveniently omits, is that the `_getDecipheredURLs` function is never called, so the screenshot proves nothing.

**Comment by mytja** [comment] 2021-07-25 17:26
> What you screenshot conveniently omits, is that the `_getDecipheredURLs` function is never called, so the screenshot proves nothing.

How do you say it's never called???
Have a look at this
https://github.com/alexmercerind/youtube-search-python/blob/539137a435a63a59612f69ba85a501ca768c12d7/youtubesearchpython/streamurlfetcher.py#L51

**Comment by 89z** [comment] 2021-07-25 17:27
Try it yourself. Add a `print` statement at the top of the function, you will see that regardless of any apparent call, the function is not actually being called by your screenshot code.

**Comment by mytja** [comment] 2021-07-25 17:33
![ytsearch2](https://user-images.githubusercontent.com/52399966/126908027-e716ae7b-3634-4824-bddb-91088cb0f02e.PNG)
![ytsearch1](https://user-images.githubusercontent.com/52399966/126908028-5c648212-3c0f-4dc9-816c-bc652defb800.PNG)
Minimum reproducible sample:
```py
from youtubesearchpython import *
fetcher = StreamURLFetcher()
video = Video.get("https://www.youtube.com/watch?v=aqz-KE-bpKQ")
url = fetcher.get(video, 251)
print(url)
```

**Comment by 89z** [comment] 2021-07-25 17:34
Correction. The function is being called, but that request is never made because of this line:

https://github.com/alexmercerind/youtube-search-python/blob/539137a435a63a59612f69ba85a501ca768c12d7/youtubesearchpython/internal/streamurlfetcher.py#L34

**Comment by mytja** [comment] 2021-07-25 17:34
Yes, because this IS NOT A AGE RESTRICTED VIDEO, as it clearly states on this line:
https://github.com/alexmercerind/youtube-search-python/blob/539137a435a63a59612f69ba85a501ca768c12d7/youtubesearchpython/internal/streamurlfetcher.py#L36

**Comment by mytja** [comment] 2021-07-25 17:35
> [This](https://github.com/alexmercerind/youtube-search-python/blob/539137a435a63a59612f69ba85a501ca768c12d7/youtubesearchpython/internal/streamurlfetcher.py#L37) is used in age-restricted videos - but I don't know if it works in not age-restricted videos (I assume not) - as you can clearly see from previous line (comment).
> [This](https://github.com/alexmercerind/youtube-search-python/blob/539137a435a63a59612f69ba85a501ca768c12d7/youtubesearchpython/internal/extras.py#L8) class directly parses YouTube's response (with stream URLs). StreamURLFetcher only descrambles those and then returns it.

Read this. It explains everything

**Comment by 89z** [comment] 2021-07-25 17:36
I promise you, if you can provide some code WHERE THE REQUEST IS ACTUALLY MADE, it will fail every time.

You have yet to do that. Every single comment youve made, none have actually made the request in question. Until that happens my original posted issue is still valid, as you have yet to actually invalidate the original point in the original post.

**Comment by mytja** [comment] 2021-07-25 17:38
> I promise you, if you can provide some code WHERE THE REQUEST IS ACTUALLY MADE, it will fail every time.

Have a look at this library's Video, VideoInternal, StreamURLFetcher and StreamURLFetcherInternal classes. It is all crystally clear, and @ alexmercerind made beautiful comments everywhere. As you can see, this function makes request to non-agerestricted videos: https://github.com/alexmercerind/youtube-search-python/blob/539137a435a63a59612f69ba85a501ca768c12d7/youtubesearchpython/internal/extras.py#L31

**Comment by 89z** [comment] 2021-07-25 17:40
Im just going to repeat myself, since you didnt actually refute my previous comment.

Unless you can provide an example program, THAT ACTUALLY MAKES THE REQUEST TO `/get_video_info`, you havent disproven anything, and my original post is still valid. NONE of the code youve provided so far actually MAKES THE `/get_video_info` request, it skips it when it hits the `if` statement.

**Comment by mytja** [comment] 2021-07-25 17:45
> Im just going to repeat myself, since you didnt actually refute my previous comment.
> 
> Unless you can provide an example program, THAT ACTUALLY MAKES THE REQUEST TO `/get_video_info`, you havent disproven anything, and my original post is still valid. NONE of the code youve provided so far actually MAKES THE `/get_video_info` request, it skips it when it hits the `if` statement.

You are right. This library uses get_video_info request in StreamURLFetcher class, but only for age restricted videos. You want to request to get_video_info, but not through this library. Thus this issue is clearly off topic. But age-restricted videos also don't work on this library. I have noticed that around 1 month ago. Maybe YouTube has removed this URL, and thus I cannot help you anymore.
Thanks for your patience

**Comment by 89z** [comment] 2021-07-25 17:48
I am just going to repeat myself, as you seem unable to disprove my point. This code:

https://github.com/alexmercerind/youtube-search-python/blob/539137a435a63a59612f69ba85a501ca768c12d7/youtubesearchpython/internal/streamurlfetcher.py#L37-L47

Is dead code, its never called and you have yet to disprove that. If you actually manage to present some code that does call it, you will see that the request fails every time, regardless of any variables.

**Comment by mytja** [comment] 2021-07-25 17:52
> I am just going to repeat myself, as you seem unable to disprove my point. This code:
> 
> https://github.com/alexmercerind/youtube-search-python/blob/539137a435a63a59612f69ba85a501ca768c12d7/youtubesearchpython/internal/streamurlfetcher.py#L37-L47
> 
> Is dead code, its never called and you have yet to disprove that. If you actually manage to present some code that does call it, you will see that the request fails every time, regardless of any variables.

That is true. It is called if this is an age-restricted video. And yes, it fails to request. And I clearly don't know what is wrong. But this people over at PyTube, which use same code for requesting, as you showed before (eg. get_video_info code), have noticed some strange behaviour, as you can clearly see on this issue: https://github.com/pytube/pytube/issues/1069
Once guys there fix it, I will fix it also here. Until then, I cannot do anything.
Thanks

**Comment by 89z** [comment] 2021-07-25 17:54
Since you admit that I am right, why is the issue still closed?

**Comment by mytja** [comment] 2021-07-25 17:55
Here you go, since you want this so bad

**Comment by mytja** [comment] 2021-07-25 18:16
This is quote from PyTube's maintainer:
> The upcoming fix will require authentication for age-restricted videos. For end users, this will prompt the user to go to a webpage and enter a code to allow access to their account. There does not appear to be a way around this, as YouTube is actively killing off the endpoint we used to rely on. I don't think that you will need to make changes to your code, unless you're accessing unusual parts of the YouTube object.
We are not using get_video_info anywhere else, than on Age-restricted videos StreamURLFetcher, and since this feature is depricated and they require age verification (as quote said - YouTube is actively killing off the endpont), I have no other choice than to close this issue.

I hope you understand and sorry for the mess

**Comment by 89z** [comment] 2021-07-25 18:17
why have you closed the issue, if the code still exists?

https://github.com/alexmercerind/youtube-search-python/blob/539137a435a63a59612f69ba85a501ca768c12d7/youtubesearchpython/internal/streamurlfetcher.py#L37-L47

**Comment by mytja** [comment] 2021-07-25 18:18
I will remove it later

**Comment by 89z** [comment] 2021-07-25 18:18
OK, but until the code is removed, this is still a valid issue...

**Comment by mytja** [comment] 2021-07-25 18:23
Yes, it is. But I am not going to reopen it. I won't forget if you are worried about that.
Thank you

**Comment by mytja** [comment] 2021-07-26 08:06
Hello!
Thanks for explanation. I didn't quite clearly understand what you meant yesterday (I was kinda in a bad mood). I am really really sorry. I will reopen issue and once I will fix this, I will close this issue. Also, if you want to fix this, you may open a PR anytime. I would be happy to merge it :wink: . I have cleared some comments, so now everything is easier to read. I will do my best to fix this as soon as possible. And by the way, thanks for your [https://github.com/pytube/pytube/issues/1060#issuecomment-886057488](comment). It works pretty well.
Again, so sorry for the mess

**Comment by alexmercerind** [comment] 2021-08-11 07:58
Not much aware of whatever happened here.
But, it does not fail now. Closing issue.

**Closed by alexmercerind** 2021-08-11 07:58 UTC
Labels: bug
