### ISSUE TITLE
Playlist search: index out of range

### ISSUE THREAD

**Issue by tobip** [alexmercerind/youtube-search-python#14] opened 2020-07-11 09:41 UTC
Thanks for the new Playlist Search feature, it is awesome!

When I search for Playlits called "drum and bass" I run into an error:

```
>>> search = SearchPlaylists("drum and bass", offset = 1, mode = "dict", max_results = 20).result()

~/.local/lib/python3.8/site-packages/youtubesearchpython/playlist__search.py in result(self)
     63                         "id": self.ids[index],
     64                         "link": self.links[index],
---> 65                         "title": self.titles[index],
     66                     }
     67                     result+=[result_index]

IndexError: list index out of range
```

Apparently `search.ids` and `search.links` have 21 entries, while `search.titles` only has 20.

**Comment by alexmercerind** [comment] 2020-07-11 12:02
Hi there @tobip!

I appreciate your feedback. I'm really confused about this bug. I'm unable to reproduce this, even after searching the same keyword as you.
Are you using the latest version (v1.2.5) ?

Thankyou for your feedback!

**Comment by tobip** [comment] 2020-07-11 14:19
Yes I am using the latest version 1.2.5.

Attached is a dump of the variables contents, if that helps.

[search_dump.txt](https://github.com/alexmercerind/youtube-search-python/files/4906899/search_dump.txt)

**Comment by alexmercerind** [comment] 2020-07-11 17:37
Thankyou 😃!

The problem is that, for some reason you are getting the watch later playlist as well in your result. That shouldn't happen.
Now what I have decided is to just pop the "WL" id and link out of the result.
It should solve the problem, at the moment at least.

**Comment by alexmercerind** [comment] 2020-07-11 18:11
Let me know if latest commit fixes the things for you!
Closing the issue. Feel free to reopen, incase you feel it.

alexmercerind@4d09bd409b2b4d31976f8d382546013c96104d23

Thankyou for support!

**Closed by alexmercerind** 2020-07-11 18:11 UTC
Labels: bug, needs info

**Comment by tobip** [comment] 2020-07-17 17:01
Thanks for your quick and nice workaround!
Works great for me now :-)

**Comment by alexmercerind** [comment] 2020-07-17 17:09
I'm glad.
